"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";

type User = { id:string; name:string; email:string; role:"admin"|"operator"|"viewer"; active?:boolean; avatar_path?:string; created_at?:string };
type Branding = Record<string, string | number | null>;
type Domain = { id:string; name:string; tld?:string; provider?:string; current_price?:number; registered_at?:string; last_renewed_at?:string; expires_at?:string; renewal_price?:number; currency:string; hosting?:string; dns_provider?:string; notes?:string; free_tier:boolean; cloudflare_connection_id?:string; cloudflare_connection_name?:string; subdomain_count:number };
type Subdomain = { id:string; name:string; dns_name?:string; record_type?:string; service?:string; host?:string; path?:string; ipv4?:string; proxied?:boolean; source:string; notes?:string };
type Disk = { device:string; mount:string; total:number; used:number; free?:number; percent:number };
type MetricPoint = { cpu:number; ram:number; temperature?:number; recorded_at:string };
type Server = { id:string; agent_id:string; name:string; location?:string; os?:string; ipv4?:string; wan_ipv4?:string; last_seen_at?:string; enrolled_at?:string; agent_version?:string; icon_path?:string; refresh_interval_ms?:number; cpu?:number; ram?:number; temperature?:number; uptime_seconds?:number; load1?:number; disks?:Disk[]; proxies?:Array<Record<string,string>> };
type Alert = { id:string; severity:string; title:string; message:string; resolved_at?:string; created_at:string };
type Connection = { id:string; name:string; account_hint?:string };
type View = "overview"|"domains"|"servers"|"server-detail"|"alerts"|"users"|"settings";

const nav:Array<[View,string,string]> = [["overview","Overview","⌂"],["domains","Domains","◎"],["servers","Servers","▤"],["alerts","Alerts","!"],["users","Users","♙"],["settings","Settings","⚙"]];
const money=(value:number|string|undefined,currency="INR")=>value==null||value===""?"—":new Intl.NumberFormat("en-IN",{style:"currency",currency,maximumFractionDigits:0}).format(Number(value));
const bytes=(value=0)=>`${(value/1073741824).toFixed(value>107374182400?0:1)} GB`;
const daysUntil=(value?:string)=>value?Math.ceil((new Date(value).getTime()-Date.now())/86400000):null;
const dateOnly=(value?:string)=>value?value.slice(0,10):"";
const uptime=(seconds=0)=>seconds?`${Math.floor(seconds/86400)}d ${Math.floor((seconds%86400)/3600)}h ${Math.floor((seconds%3600)/60)}m`:"Waiting";

async function api(url:string,options?:RequestInit){const response=await fetch(url,{cache:"no-store",...options});const data=response.headers.get("content-type")?.includes("json")?await response.json():null;if(!response.ok)throw new Error(data?.error||`Request failed (${response.status})`);return data}

export default function Dashboard({initialUser,initialBranding}:{initialUser:User;initialBranding:Branding}){
  const [view,setView]=useState<View>("overview"),[dark,setDark]=useState(false),[themeReady,setThemeReady]=useState(false),[mobile,setMobile]=useState(false);
  const [domains,setDomains]=useState<Domain[]>([]),[servers,setServers]=useState<Server[]>([]),[alerts,setAlerts]=useState<Alert[]>([]),[users,setUsers]=useState<User[]>([]),[connections,setConnections]=useState<Connection[]>([]);
  const [branding,setBranding]=useState(initialBranding),[notifications,setNotifications]=useState<Record<string,string|number|null>>({}),[query,setQuery]=useState(""),[busy,setBusy]=useState(false),[toast,setToast]=useState("");
  const [clock,setClock]=useState(0);
  const [modal,setModal]=useState<string|null>(null),[selectedDomain,setSelectedDomain]=useState<Domain|null>(null),[selectedSubdomain,setSelectedSubdomain]=useState<Subdomain|null>(null),[subdomains,setSubdomains]=useState<Subdomain[]>([]),[dns,setDns]=useState<Array<Record<string,unknown>>>([]);
  const [selectedServer,setSelectedServer]=useState<Server|null>(null),[serverMetrics,setServerMetrics]=useState<MetricPoint[]>([]),[selectedUser,setSelectedUser]=useState<User|null>(null),[install,setInstall]=useState("");
  const [domainSort,setDomainSort]=useState("name"),[domainDirection,setDomainDirection]=useState<"asc"|"desc">("asc"),[subdomainSort,setSubdomainSort]=useState("name");
  const tell=(message:string)=>{setToast(message);window.setTimeout(()=>setToast(""),4000)};

  const load=useCallback(async()=>{const [d,s,a,b,c]=await Promise.all([api("/api/domains"),api("/api/servers"),api("/api/alerts"),api("/api/branding"),api("/api/cloudflare/connections")]);setDomains(d.domains);setServers(s.servers);setAlerts(a.alerts);setBranding(b.branding);setConnections(c.connections);if(initialUser.role==="admin"){const [u,n]=await Promise.all([api("/api/users"),api("/api/settings/notifications")]);setUsers(u.users);setNotifications(n.settings)}},[initialUser.role]);
  const loadServer=useCallback(async(id:string)=>{const result=await api(`/api/servers/${id}`);setSelectedServer(result.server);setServerMetrics(result.metrics)},[]);
  useEffect(()=>{const start=window.setTimeout(()=>load().catch(e=>tell(e.message)),0);const timer=window.setInterval(()=>load().catch(()=>{}),30000);return()=>{clearTimeout(start);clearInterval(timer)}},[load]);
  useEffect(()=>{const timer=window.setTimeout(()=>{setDark(localStorage.getItem("nexus-theme")==="dark");setThemeReady(true);setClock(Date.now())},0);const ticker=window.setInterval(()=>setClock(Date.now()),1000);return()=>{clearTimeout(timer);clearInterval(ticker)}},[]);
  useEffect(()=>{if(!themeReady)return;document.documentElement.classList.toggle("dark",dark);localStorage.setItem("nexus-theme",dark?"dark":"light")},[dark,themeReady]);
  useEffect(()=>{if(!branding.favicon_path)return;let link=document.querySelector<HTMLLinkElement>('link[rel="icon"]');if(!link){link=document.createElement("link");link.rel="icon";document.head.appendChild(link)}link.href=String(branding.favicon_path)},[branding.favicon_path]);
  useEffect(()=>{if(view!=="server-detail"||!selectedServer?.id)return;const ms=Math.max(1000,Number(selectedServer.refresh_interval_ms||1000));const timer=window.setInterval(()=>loadServer(selectedServer.id).catch(()=>{}),ms);return()=>clearInterval(timer)},[view,selectedServer?.id,selectedServer?.refresh_interval_ms,loadServer]);

  const style={"--primary":String(branding.primary_color||"#2563eb"),"--accent":String(branding.accent_color||"#7c3aed"),"--font":String(branding.font_family||"Inter"),"--base-size":`${branding.base_font_size||15}px`} as React.CSSProperties;
  const online=(s:Server)=>Boolean(clock&&s.last_seen_at&&clock-new Date(s.last_seen_at).getTime()<Math.max(90000,Number(s.refresh_interval_ms||1000)*4));
  const filtered=useMemo(()=>domains.filter(d=>`${d.name} ${d.provider||""} ${d.hosting||""} ${d.dns_provider||""}`.toLowerCase().includes(query.toLowerCase())),[domains,query]);
  const sorted=useMemo(()=>[...filtered].sort((a,b)=>{const values=(d:Domain)=>domainSort==="provider"?d.provider||"":domainSort==="expires"?d.expires_at||"9999":domainSort==="time"?daysUntil(d.expires_at)??999999:domainSort==="price"?Number(d.renewal_price||0):d.name;const av=values(a),bv=values(b);const result=typeof av==="number"&&typeof bv==="number"?av-bv:String(av).localeCompare(String(bv));return domainDirection==="asc"?result:-result}),[filtered,domainSort,domainDirection]);
  const openAlerts=alerts.filter(a=>!a.resolved_at),renewalTotal=domains.reduce((sum,d)=>sum+Number(d.renewal_price||0),0);

  async function openDomain(domain:Domain){setSelectedDomain(domain);setDns([]);const result=await api(`/api/domains/${domain.id}`);setSubdomains(result.subdomains);setModal("domain-detail")}
  async function removeDomain(domain:Domain){if(!confirm(`Delete ${domain.name} and all of its subdomains?`))return;await api(`/api/domains/${domain.id}`,{method:"DELETE"});await load();tell("Domain deleted")}
  async function submitDomain(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);try{const f=new FormData(event.currentTarget);let connectionId=String(f.get("cloudflareConnectionId")||"")||null;const token=String(f.get("cloudflareToken")||"");if(token){const c=await api("/api/cloudflare/connections",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name:f.get("cloudflareName")||f.get("name"),token})});connectionId=c.id}const payload={name:f.get("name"),provider:f.get("provider"),currentPrice:Number(f.get("currentPrice"))||null,registeredAt:f.get("registeredAt")||null,lastRenewedAt:f.get("lastRenewedAt")||null,expiresAt:f.get("expiresAt")||null,renewalPrice:Number(f.get("renewalPrice"))||null,currency:f.get("currency")||"INR",hosting:f.get("hosting"),dnsProvider:f.get("dnsProvider"),notes:f.get("notes"),freeTier:f.get("freeTier")==="on",cloudflareConnectionId:connectionId};await api(selectedDomain?`/api/domains/${selectedDomain.id}`:"/api/domains",{method:selectedDomain?"PATCH":"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});setModal(null);setSelectedDomain(null);await load();tell(selectedDomain?"Domain updated":"Domain added")}catch(e){tell((e as Error).message)}finally{setBusy(false)}}
  async function renew(domain:Domain){const date=domain.expires_at?new Date(domain.expires_at):new Date();date.setFullYear(date.getFullYear()+1);await api(`/api/domains/${domain.id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({name:domain.name,provider:domain.provider,currentPrice:domain.current_price,registeredAt:domain.registered_at,lastRenewedAt:new Date().toISOString().slice(0,10),expiresAt:date.toISOString().slice(0,10),renewalPrice:domain.renewal_price,currency:domain.currency,hosting:domain.hosting,dnsProvider:domain.dns_provider,notes:domain.notes,freeTier:domain.free_tier,cloudflareConnectionId:domain.cloudflare_connection_id,markRenewed:true})});await load();tell("Renewal recorded")}
  async function submitSubdomain(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!selectedDomain)return;const f=new FormData(event.currentTarget);const id=String(f.get("id")||"");await api(id?`/api/subdomains/${id}`:`/api/domains/${selectedDomain.id}/subdomains`,{method:id?"PATCH":"POST",headers:{"content-type":"application/json"},body:JSON.stringify(Object.fromEntries(f))});const result=await api(`/api/domains/${selectedDomain.id}`);setSubdomains(result.subdomains);setSelectedSubdomain(null);setModal("domain-detail");tell("Subdomain saved")}
  async function removeSubdomain(item:Subdomain){if(!confirm(`Delete ${item.name}?`))return;await api(`/api/subdomains/${item.id}`,{method:"DELETE"});if(selectedDomain){const result=await api(`/api/domains/${selectedDomain.id}`);setSubdomains(result.subdomains)}tell("Subdomain deleted")}
  async function importExcel(file?:File){if(!file)return;const form=new FormData();form.set("file",file);setBusy(true);try{const r=await api("/api/domains/import",{method:"POST",body:form});await load();tell(`${r.importedDomains} domains and ${r.importedSubdomains} subdomains imported`)}catch(e){tell((e as Error).message)}finally{setBusy(false)}}

  async function addServer(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);try{const result=await api("/api/servers",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(Object.fromEntries(new FormData(event.currentTarget)))});setInstall(result.installCommand);setModal("install");await load()}catch(e){tell((e as Error).message)}finally{setBusy(false)}}
  async function saveServer(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!selectedServer)return;const f=new FormData(event.currentTarget);await api(`/api/servers/${selectedServer.id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({name:f.get("name"),location:f.get("location"),os:f.get("os"),ipv4:f.get("ipv4"),refreshIntervalMs:Number(f.get("refreshIntervalMs"))})});const icon=f.get("icon");if(icon instanceof File&&icon.size){const upload=new FormData();upload.set("file",icon);await api(`/api/servers/${selectedServer.id}/icon`,{method:"POST",body:upload})}await loadServer(selectedServer.id);await load();setModal(null);tell("Server settings saved")}
  async function removeServer(server:Server){if(!confirm(`Delete ${server.name} and its telemetry history?`))return;await api(`/api/servers/${server.id}`,{method:"DELETE"});setView("servers");setSelectedServer(null);await load();tell("Server deleted")}
  async function openServer(server:Server){setSelectedServer(server);setServerMetrics([]);setView("server-detail");await loadServer(server.id)}

  async function submitUser(event:FormEvent<HTMLFormElement>){event.preventDefault();const f=new FormData(event.currentTarget);const editing=Boolean(selectedUser);const body={name:f.get("name"),email:f.get("email"),password:f.get("password")||undefined,role:f.get("role"),active:f.get("active")==="on"};const result=await api(editing?`/api/users/${selectedUser!.id}`:"/api/users",{method:editing?"PATCH":"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});const id=selectedUser?.id||result.id;const photo=f.get("photo");if(photo instanceof File&&photo.size){const upload=new FormData();upload.set("file",photo);await api(`/api/users/${id}/photo`,{method:"POST",body:upload})}setSelectedUser(null);setModal(null);await load();tell(editing?"User updated":"User created")}
  async function removeUser(user:User){if(user.role==="admin")return;if(!confirm(`Delete ${user.name}?`))return;await api(`/api/users/${user.id}`,{method:"DELETE"});await load();tell("User deleted")}
  async function saveBranding(event:FormEvent<HTMLFormElement>){event.preventDefault();await api("/api/branding",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify(Object.fromEntries(new FormData(event.currentTarget)))});await load();tell("Theme applied")}
  async function uploadBrand(kind:string,file?:File){if(!file)return;const form=new FormData();form.set("kind",kind);form.set("file",file);await api("/api/branding",{method:"POST",body:form});await load();tell("Image uploaded")}
  async function deleteConnection(connection:Connection){if(!confirm(`Delete Cloudflare connection ${connection.name}? Domains will be disconnected.`))return;await api(`/api/cloudflare/connections?id=${connection.id}`,{method:"DELETE"});await load();tell("Cloudflare token deleted")}
  async function saveNotifications(event:FormEvent<HTMLFormElement>){event.preventDefault();await api("/api/settings/notifications",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify(Object.fromEntries(new FormData(event.currentTarget)))});await load();tell("Alert settings saved")}

  const title=view==="server-detail"?selectedServer?.name:nav.find(x=>x[0]===view)?.[1];
  return <div className="app-shell" style={style}>
    <aside className={`sidebar ${mobile?"open":""}`}><button className="mobile-close" onClick={()=>setMobile(false)}>×</button><div className="brand">{branding.logo_path?<img src={String(branding.logo_path)} alt=""/>:<span className="brand-mark">N</span>}<span><strong>{branding.brand_name||"Nexus"}</strong><small>{branding.brand_tagline}</small></span></div><nav><p className="nav-label">Workspace</p>{nav.filter(([id])=>id!=="users"||initialUser.role==="admin").map(([id,label,icon])=><button key={id} className={(view===id||(view==="server-detail"&&id==="servers"))?"active":""} onClick={()=>{setView(id);setMobile(false)}}><span>{icon}</span>{label}{id==="alerts"&&openAlerts.length>0?<b className="nav-badge">{openAlerts.length}</b>:null}</button>)}</nav><div className="sidebar-card"><span className="pulse-dot"/><div><strong>Monitoring active</strong><small>{servers.filter(online).length} of {servers.length} agents online</small></div></div><div className="profile">{initialUser.avatar_path?<img className="avatar image" src={initialUser.avatar_path} alt=""/>:<div className="avatar">{initialUser.name.split(" ").map(x=>x[0]).slice(0,2).join("")}</div>}<div><strong>{initialUser.name}</strong><small>{initialUser.role}</small></div><button onClick={async()=>{await api("/api/auth/logout",{method:"POST"});location.href="/login"}}>↪</button></div></aside>
    <main><header className="topbar"><button className="menu-button" onClick={()=>setMobile(true)}>☰</button><label className="search">⌕<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search domains, providers, hosting…"/></label><div className="top-actions"><button className="icon-button" onClick={()=>setDark(!dark)}>{dark?"☀":"☾"}</button>{view==="domains"&&<button className="primary-button" onClick={()=>{setSelectedDomain(null);setModal("domain-form")}}>＋ Add domain</button>}{view==="servers"&&<button className="primary-button" onClick={()=>setModal("server-form")}>＋ Add server</button>}</div></header>
      <div className="content"><section className="welcome"><div><p className="eyebrow">Infrastructure command center</p><h1>{view==="overview"?`Welcome back, ${initialUser.name.split(" ")[0]}.`:title}</h1><p>{view==="server-detail"?"Live telemetry from the installed Nexus agent.":"Every control here is connected to real data."}</p></div><button className="secondary-button" onClick={()=>load().then(()=>tell("Data refreshed"))}>↻ Refresh</button></section>
      {view==="overview"&&<><section className="kpi-grid"><Kpi label="Managed domains" value={String(domains.length)} note={`${domains.filter(d=>(daysUntil(d.expires_at)||999)<60).length} renew within 60 days`} tone="blue"/><Kpi label="Servers online" value={`${servers.filter(online).length}/${servers.length}`} note="Live agent status" tone="purple"/><Kpi label="Annual renewals" value={money(renewalTotal)} note="Paid portfolio estimate" tone="green"/><Kpi label="Open alerts" value={String(openAlerts.length)} note="Email and webhook enabled" tone="orange"/></section><ServerTiles servers={servers} online={online} open={openServer}/><DomainTable domains={sorted.filter(d=>!d.free_tier).slice(0,8)} open={openDomain} edit={d=>{setSelectedDomain(d);setModal("domain-form")}} renew={renew} remove={removeDomain}/></>}
      {view==="domains"&&<section className="panel"><div className="panel-heading"><div><h2>Domain portfolio</h2><p>Paid and free domains are separated below.</p></div><div className="button-row"><label className="secondary-button file-button">{busy?"Importing…":"Import Excel"}<input type="file" accept=".xlsx,.xlsm" onChange={e=>{const file=e.currentTarget.files?.[0];e.currentTarget.value="";void importExcel(file)}}/></label><button className="secondary-button" onClick={()=>location.href="/api/domains/export"}>Export / template</button><select className="sort-select" value={domainSort} onChange={e=>setDomainSort(e.target.value)}><option value="name">Name A–Z</option><option value="provider">Provider</option><option value="expires">Expires</option><option value="time">Time left</option><option value="price">Renewal price</option></select><button className="secondary-button" onClick={()=>setDomainDirection(x=>x==="asc"?"desc":"asc")}>{domainDirection==="asc"?"↑ Asc":"↓ Desc"}</button><button className="primary-button" onClick={()=>{setSelectedDomain(null);setModal("domain-form")}}>＋ Add domain</button></div></div><h3 className="table-title">Paid domains <span>{sorted.filter(d=>!d.free_tier).length}</span></h3><DomainTable domains={sorted.filter(d=>!d.free_tier)} open={openDomain} edit={d=>{setSelectedDomain(d);setModal("domain-form")}} renew={renew} remove={removeDomain}/><h3 className="table-title lower">Free domains <span>{sorted.filter(d=>d.free_tier).length}</span></h3><DomainTable domains={sorted.filter(d=>d.free_tier)} open={openDomain} edit={d=>{setSelectedDomain(d);setModal("domain-form")}} renew={renew} remove={removeDomain}/></section>}
      {view==="servers"&&<section className="panel"><div className="panel-heading"><div><h2>Server fleet</h2><p>Select a tile for its real-time telemetry page.</p></div><button className="primary-button" onClick={()=>setModal("server-form")}>＋ Add server</button></div><ServerTiles servers={servers} online={online} open={openServer} edit={s=>{setSelectedServer(s);setModal("server-edit")}} settings={s=>{setSelectedServer(s);setModal("server-settings")}} remove={removeServer}/></section>}
      {view==="server-detail"&&selectedServer&&<ServerDetail server={selectedServer} metrics={serverMetrics} online={online(selectedServer)} back={()=>setView("servers")} settings={()=>setModal("server-settings")}/>}
      {view==="alerts"&&<section className="panel"><div className="panel-heading"><div><h2>Alerts</h2><p>Offline servers and upcoming renewals.</p></div></div><div className="alert-list">{alerts.map(a=><article className={a.resolved_at?"resolved":""} key={a.id}><span className={`severity ${a.severity}`}>!</span><div><strong>{a.title}</strong><p>{a.message}</p><small>{new Date(a.created_at).toLocaleString()}</small></div>{!a.resolved_at&&<button className="secondary-button" onClick={async()=>{await api("/api/alerts",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id:a.id,resolved:true})});await load()}}>Resolve</button>}</article>)}</div></section>}
      {view==="users"&&initialUser.role==="admin"&&<section className="panel"><div className="panel-heading"><div><h2>User management</h2><p>Administrator accounts are protected from edit and deletion.</p></div><button className="primary-button" onClick={()=>{setSelectedUser(null);setModal("user-form")}}>＋ Add user</button></div><div className="user-grid">{users.map(u=><article key={u.id}>{u.avatar_path?<img className="avatar image" src={u.avatar_path} alt=""/>:<div className="avatar">{u.name[0]}</div>}<div><strong>{u.name}</strong><p>{u.email}</p></div><span className="role-pill">{u.role}</span><div className="row-actions"><button onClick={()=>{setSelectedUser(u);setModal("user-view")}}>View</button>{u.role!=="admin"&&<><button onClick={()=>{setSelectedUser(u);setModal("user-form")}}>Edit</button><button className="danger-text" onClick={()=>removeUser(u)}>Delete</button></>}</div></article>)}</div></section>}
      {view==="settings"&&<Settings branding={branding} notifications={notifications} connections={connections} saveBranding={saveBranding} saveNotifications={saveNotifications} upload={uploadBrand} removeConnection={deleteConnection}/>}<footer>{branding.brand_name||"Nexus"} · PostgreSQL backed · Agent API v3</footer></div></main>
    {toast&&<div className="toast">{toast}</div>}
    {modal&&<div className="modal-backdrop" onMouseDown={()=>setModal(null)}><div className={`modal ${modal==="domain-detail"?"wide":""}`} onMouseDown={e=>e.stopPropagation()}><button className="modal-close" onClick={()=>setModal(null)}>×</button>
      {modal==="domain-form"&&<DomainForm domain={selectedDomain} connections={connections} submit={submitDomain} busy={busy}/>} {modal==="domain-detail"&&selectedDomain&&<DomainDetail domain={selectedDomain} subdomains={subdomains} dns={dns} sort={subdomainSort} setSort={setSubdomainSort} add={()=>{setSelectedSubdomain(null);setModal("subdomain-form")}} edit={s=>{setSelectedSubdomain(s);setModal("subdomain-form")}} remove={removeSubdomain} loadDns={async()=>{const r=await api(`/api/domains/${selectedDomain.id}/dns`);setDns(r.records)}} sync={async()=>{const r=await api(`/api/domains/${selectedDomain.id}/dns`,{method:"POST"});const detail=await api(`/api/domains/${selectedDomain.id}`);setSubdomains(detail.subdomains);tell(`${r.imported} Cloudflare records synced`)}}/>} {modal==="subdomain-form"&&selectedDomain&&<SubdomainForm item={selectedSubdomain} submit={submitSubdomain}/>}
      {modal==="server-form"&&<ServerCreate submit={addServer} busy={busy}/>} {(modal==="server-edit"||modal==="server-settings")&&selectedServer&&<ServerSettings server={selectedServer} submit={saveServer} settings={modal==="server-settings"}/>} {modal==="install"&&<Install command={install}/>} {modal==="user-form"&&<UserForm user={selectedUser} submit={submitUser}/>} {modal==="user-view"&&selectedUser&&<UserView user={selectedUser}/>} </div></div>}
  </div>
}

function Kpi({label,value,note,tone}:{label:string;value:string;note:string;tone:string}){return <article className={`kpi ${tone}`}><span>{label}</span><strong>{value}</strong><small>{note}</small></article>}
function DomainTable({domains,open,edit,renew,remove}:{domains:Domain[];open:(d:Domain)=>void;edit:(d:Domain)=>void;renew:(d:Domain)=>void;remove:(d:Domain)=>void}){return <div className="table-wrap"><table><thead><tr><th>Domain</th><th>Provider</th><th>Hosting</th><th>Expires</th><th>Time left</th><th>Renewal</th><th>Actions</th></tr></thead><tbody>{domains.map(d=>{const days=daysUntil(d.expires_at);return <tr key={d.id} onClick={()=>open(d)}><td><strong>{d.name}</strong><small>{d.dns_provider||"DNS not set"} · {d.subdomain_count||0} subdomains</small></td><td>{d.provider||"—"}</td><td>{d.hosting||"Unassigned"}</td><td>{dateOnly(d.expires_at)||"—"}</td><td><span className={`days-pill ${(days??999)<60?"urgent":(days??999)<180?"soon":"safe"}`}>{days==null?"Unknown":days<0?`${Math.abs(days)}d overdue`:`${days} days`}</span></td><td>{d.free_tier?"Free":money(d.renewal_price,d.currency)}</td><td><div className="row-actions"><button onClick={e=>{e.stopPropagation();edit(d)}}>Edit</button><button onClick={e=>{e.stopPropagation();renew(d)}}>Renewed</button><button className="danger-text" onClick={e=>{e.stopPropagation();remove(d)}}>Delete</button></div></td></tr>})}</tbody></table>{!domains.length&&<div className="empty-state">No domains here.</div>}</div>}
function ServerTiles({servers,online,open,edit,settings,remove}:{servers:Server[];online:(s:Server)=>boolean;open:(s:Server)=>void;edit?:(s:Server)=>void;settings?:(s:Server)=>void;remove?:(s:Server)=>void}){return <div className="server-grid">{servers.map(s=><article className="server-card tile" key={s.id} onClick={()=>open(s)}><div className="server-title">{s.icon_path?<img className="server-icon" src={s.icon_path} alt=""/>:<span className={`server-status ${online(s)?"online":"offline"}`}/>}<div><h3>{s.name}</h3><p>{s.ipv4||"No LAN IP"} · {s.location||"Location not set"}</p></div><span className="role-pill">{online(s)?"Online":"Offline"}</span>{settings&&<details className="more-menu" onClick={e=>e.stopPropagation()}><summary>⋮</summary><div><button onClick={()=>edit?.(s)}>Edit</button><button onClick={()=>settings(s)}>Settings</button><button className="danger-text" onClick={()=>remove?.(s)}>Delete</button></div></details>}</div><div className="tile-stats"><span>CPU <b>{Math.round(Number(s.cpu||0))}%</b></span><span>RAM <b>{Math.round(Number(s.ram||0))}%</b></span><span>Temp <b>{s.temperature==null?"N/A":`${Math.round(Number(s.temperature))}°C`}</b></span></div></article>)}{!servers.length&&<div className="empty-state">Add a server to generate its one-time agent command.</div>}</div>}
function Metric({label,value,suffix="%"}:{label:string;value:number|null;suffix?:string}){return <div><span>{label}</span><strong>{value==null?"N/A":`${Math.round(value)}${suffix}`}</strong><i><b style={{width:`${Math.min(100,value||0)}%`}}/></i></div>}
function ServerDetail({server,metrics,online,back,settings}:{server:Server;metrics:MetricPoint[];online:boolean;back:()=>void;settings:()=>void}){return <section className="panel server-detail"><div className="panel-heading"><div className="button-row"><button className="secondary-button" onClick={back}>← Servers</button><span className={`status-chip ${online?"online":"offline"}`}>{online?"Live":"Offline"}</span></div><button className="secondary-button" onClick={settings}>⚙ Settings</button></div><div className="live-strip"><span className="pulse-dot"/><b>REAL-TIME STATS</b><small>Updated {server.last_seen_at?new Date(server.last_seen_at).toLocaleTimeString():"never"} · every {server.refresh_interval_ms||1000} ms</small></div><div className="live-kpis"><Metric label="CPU" value={Number(server.cpu||0)}/><Metric label="RAM" value={Number(server.ram||0)}/><Metric label="TEMP" value={server.temperature==null?null:Number(server.temperature)} suffix="°C"/><div><span>LOAD</span><strong>{Number(server.load1||0).toFixed(2)}</strong></div></div><div className="telemetry-chart"><div><b>CPU history</b><small>Last {metrics.length} samples</small></div><div className="bars">{metrics.slice(-60).map((m,i)=><i key={i} title={`${m.cpu}%`} style={{height:`${Math.max(2,Number(m.cpu))}%`}}/>)}</div></div><div className="detail-grid"><span>LAN IPv4<b>{server.ipv4||"Waiting"}</b></span><span>WAN IPv4<b>{server.wan_ipv4||"Waiting"}</b></span><span>Uptime<b>{uptime(Number(server.uptime_seconds||0))}</b></span><span>Operating system<b>{server.os||"Waiting"}</b></span><span>Agent version<b>{server.agent_version||"Waiting"}</b></span><span>Proxy services<b>{(server.proxies||[]).length}</b></span></div><h3>Storage — all mounted disks</h3><div className="disk-list detailed">{(server.disks||[]).map(d=><div key={`${d.device}${d.mount}`}><span><b>{d.mount}</b><small>{d.device}</small></span><div className="disk-bar"><i style={{width:`${d.percent}%`}}/></div><b>{d.percent}% · {bytes(d.used)} / {bytes(d.total)}</b></div>)}{!(server.disks||[]).length&&<div className="empty-state">Waiting for disk inventory.</div>}</div><h3>Discovered Docker and proxy routes</h3><div className="proxy-grid">{(server.proxies||[]).map((p,i)=><code key={i}>{p.domain||p.service||p.source} → {p.target||p.path||p.image}</code>)}{!(server.proxies||[]).length&&<small>No proxy routes reported.</small>}</div></section>}
function Field({label,name,type="text",value,required,min,children}:{label:string;name:string;type?:string;value?:string|number|null;required?:boolean;min?:number;children?:React.ReactNode}){return <label>{label}{children||<input name={name} type={type} defaultValue={type==="file"?undefined:value??""} required={required} min={min}/>}</label>}
function DomainForm({domain,connections,submit,busy}:{domain:Domain|null;connections:Connection[];submit:(e:FormEvent<HTMLFormElement>)=>void;busy:boolean}){return <><p className="eyebrow">Portfolio record</p><h2>{domain?"Edit domain":"Add domain"}</h2><form onSubmit={submit}><div className="form-grid"><Field label="Domain" name="name" value={domain?.name} required/><Field label="Provider" name="provider" value={domain?.provider}/><Field label="Registration date" name="registeredAt" type="date" value={dateOnly(domain?.registered_at)}/><Field label="Last renewed" name="lastRenewedAt" type="date" value={dateOnly(domain?.last_renewed_at)}/><Field label="Expiry date" name="expiresAt" type="date" value={dateOnly(domain?.expires_at)}/><Field label="Renewal price" name="renewalPrice" type="number" value={domain?.renewal_price}/><Field label="Current price" name="currentPrice" type="number" value={domain?.current_price}/><Field label="Currency" name="currency" value={domain?.currency||"INR"}/><Field label="Hosting" name="hosting" value={domain?.hosting}/><Field label="DNS provider" name="dnsProvider" value={domain?.dns_provider}/><Field label="Cloudflare connection" name="cloudflareConnectionId"><select name="cloudflareConnectionId" defaultValue={domain?.cloudflare_connection_id||""}><option value="">None</option>{connections.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></Field><label className="check"><input type="checkbox" name="freeTier" defaultChecked={domain?.free_tier}/>Free-tier domain</label></div><details><summary>Add a new Cloudflare API token</summary><div className="form-grid"><Field label="Connection name" name="cloudflareName"/><Field label="Scoped API token" name="cloudflareToken" type="password"/></div></details><Field label="Notes" name="notes"><textarea name="notes" defaultValue={domain?.notes||""}/></Field><button className="primary-button wide" disabled={busy}>{busy?"Saving…":"Save domain"}</button></form></>}
function SubdomainForm({item,submit}:{item:Subdomain|null;submit:(e:FormEvent<HTMLFormElement>)=>void}){return <><p className="eyebrow">Route record</p><h2>{item?"Edit":"Add"} subdomain</h2><form onSubmit={submit}><input type="hidden" name="id" value={item?.id||""}/><div className="form-grid"><Field label="Full subdomain" name="name" value={item?.name} required/><Field label="DNS name" name="dnsName" value={item?.dns_name}/><Field label="Record type" name="recordType" value={item?.record_type}/><Field label="Service" name="service" value={item?.service}/><Field label="Host / server" name="host" value={item?.host}/><Field label="Path or proxy target" name="path" value={item?.path}/><Field label="IPv4" name="ipv4" value={item?.ipv4}/></div><Field label="Notes" name="notes"><textarea name="notes" defaultValue={item?.notes||""}/></Field><button className="primary-button wide">Save subdomain</button></form></>}
function DomainDetail({domain,subdomains,dns,sort,setSort,add,edit,remove,loadDns,sync}:{domain:Domain;subdomains:Subdomain[];dns:Array<Record<string,unknown>>;sort:string;setSort:(v:string)=>void;add:()=>void;edit:(s:Subdomain)=>void;remove:(s:Subdomain)=>void;loadDns:()=>void;sync:()=>void}){const items=[...subdomains].sort((a,b)=>String(sort==="type"?a.record_type||"":sort==="service"?a.service||"":sort==="host"?a.host||"":sort==="ipv4"?a.ipv4||"":a.name).localeCompare(String(sort==="type"?b.record_type||"":sort==="service"?b.service||"":sort==="host"?b.host||"":sort==="ipv4"?b.ipv4||"":b.name)));return <><p className="eyebrow">Domain overview</p><h2>{domain.name}</h2><div className="detail-grid"><span>Provider<b>{domain.provider||"—"}</b></span><span>Registered<b>{dateOnly(domain.registered_at)||"—"}</b></span><span>Expires<b>{dateOnly(domain.expires_at)||"—"}</b></span><span>Renewal<b>{domain.free_tier?"Free":money(domain.renewal_price,domain.currency)}</b></span><span>DNS provider<b>{domain.dns_provider||"—"}</b></span><span>Hosting<b>{domain.hosting||"Unassigned"}</b></span></div><div className="panel-heading compact"><div><h3>Subdomains</h3><p>Cloudflare DNS plus agent-discovered hosts and paths.</p></div><div className="button-row"><select className="sort-select" value={sort} onChange={e=>setSort(e.target.value)}><option value="name">Name A–Z</option><option value="type">Record type</option><option value="service">Service</option><option value="host">Host</option><option value="ipv4">IPv4</option></select><button className="secondary-button" onClick={loadDns}>View DNS</button><button className="secondary-button" onClick={sync}>Sync Cloudflare</button><button className="primary-button" onClick={add}>＋ Add</button></div></div><div className="table-wrap"><table><thead><tr><th>Subdomain</th><th>Type</th><th>Service</th><th>Host</th><th>Path / Target</th><th>IPv4</th><th>Actions</th></tr></thead><tbody>{items.map(s=><tr key={s.id}><td><strong>{s.name}</strong><small>{s.source}</small></td><td>{s.record_type||"—"}</td><td>{s.service||"—"}</td><td>{s.host||"—"}</td><td>{s.path||"—"}</td><td>{s.ipv4||"—"}</td><td><div className="row-actions"><button onClick={()=>edit(s)}>Edit</button><button className="danger-text" onClick={()=>remove(s)}>Delete</button></div></td></tr>)}</tbody></table>{!items.length&&<div className="empty-state">No subdomains found.</div>}</div>{dns.length>0&&<><h3>Live Cloudflare DNS records</h3><div className="dns-list">{dns.map((r,i)=><code key={i}>{String(r.type)} {String(r.name)} → {String(r.content)} {r.proxied?"(proxied)":""}</code>)}</div></>}</>}
function ServerCreate({submit,busy}:{submit:(e:FormEvent<HTMLFormElement>)=>void;busy:boolean}){return <><p className="eyebrow">Plug-and-play agent</p><h2>Add a server</h2><p>Create the record, then run the one-time command on that server.</p><form onSubmit={submit}><Field label="Server name" name="name" required/><div className="form-grid"><Field label="Known IPv4 (optional)" name="ipv4"/><Field label="Location" name="location"/><Field label="Operating system" name="os"/></div><button className="primary-button wide" disabled={busy}>{busy?"Creating…":"Create and generate command"}</button></form></>}
function ServerSettings({server,submit,settings}:{server:Server;submit:(e:FormEvent<HTMLFormElement>)=>void;settings:boolean}){return <><p className="eyebrow">{settings?"Telemetry settings":"Server record"}</p><h2>{settings?"Server settings":"Edit server"}</h2><form onSubmit={submit}><div className="form-grid"><Field label="Server name" name="name" value={server.name} required/><Field label="Location" name="location" value={server.location}/><Field label="Operating system" name="os" value={server.os}/><Field label="IPv4" name="ipv4" value={server.ipv4}/>{settings&&<Field label="Auto refresh (milliseconds)" name="refreshIntervalMs" type="number" min={1000} value={server.refresh_interval_ms||1000}/>}</div>{settings&&<Field label="Server icon / logo" name="icon" type="file"/>}<button className="primary-button wide">Save server</button></form></>}
function Install({command}:{command:string}){return <><p className="eyebrow">Server enrollment</p><h2>Install the Nexus agent</h2><p>Run this once as a sudo-capable user. The token expires in 24 hours.</p><pre className="command">{command}</pre><button className="primary-button wide" onClick={()=>navigator.clipboard.writeText(command)}>Copy command</button></>}
function UserForm({user,submit}:{user:User|null;submit:(e:FormEvent<HTMLFormElement>)=>void}){return <><p className="eyebrow">Access control</p><h2>{user?"Edit user":"Add user"}</h2><form onSubmit={submit}><Field label="Name" name="name" value={user?.name} required/><Field label="Email" name="email" type="email" value={user?.email} required/><Field label={user?"New password (optional, 12+ characters)":"Temporary password (12+ characters)"} name="password" type="password" required={!user}/><Field label="Role" name="role"><select name="role" defaultValue={user?.role||"viewer"}><option value="viewer">Viewer</option><option value="operator">Operator</option>{!user&&<option value="admin">Administrator</option>}</select></Field>{user&&<label className="check"><input type="checkbox" name="active" defaultChecked={user.active!==false}/>Active</label>}<Field label="Profile photo" name="photo" type="file"/><button className="primary-button wide">{user?"Save user":"Create user"}</button></form></>}
function UserView({user}:{user:User}){return <><p className="eyebrow">User profile</p>{user.avatar_path?<img className="profile-photo" src={user.avatar_path} alt=""/>:<div className="profile-photo fallback">{user.name[0]}</div>}<h2>{user.name}</h2><div className="detail-grid"><span>Email<b>{user.email}</b></span><span>Role<b>{user.role}</b></span><span>Status<b>{user.active===false?"Disabled":"Active"}</b></span></div></>}
function Settings({branding,notifications,connections,saveBranding,saveNotifications,upload,removeConnection}:{branding:Branding;notifications:Record<string,string|number|null>;connections:Connection[];saveBranding:(e:FormEvent<HTMLFormElement>)=>void;saveNotifications:(e:FormEvent<HTMLFormElement>)=>void;upload:(kind:string,file?:File)=>void;removeConnection:(c:Connection)=>void}){return <div className="settings-grid"><section className="panel"><div className="panel-heading"><div><h2>Branding and theme</h2><p>Changes apply to the dashboard and login page.</p></div></div><form onSubmit={saveBranding}><div className="form-grid"><Field label="Brand name" name="brandName" value={branding.brand_name}/><Field label="Tagline" name="brandTagline" value={branding.brand_tagline}/><Field label="Primary color" name="primaryColor" type="color" value={branding.primary_color}/><Field label="Accent color" name="accentColor" type="color" value={branding.accent_color}/><Field label="Font" name="fontFamily"><select name="fontFamily" defaultValue={String(branding.font_family||"Inter")}><option>Inter</option><option>Arial</option><option>Georgia</option><option>Verdana</option><option>Tahoma</option><option>Trebuchet MS</option><option>Courier New</option></select></Field><Field label="Base font size" name="baseFontSize" type="number" min={12} value={branding.base_font_size}/></div><button className="primary-button">Save and apply theme</button></form><div className="upload-grid">{[["logo","Dashboard logo"],["loginLogo","Login logo"],["favicon","Favicon"],["loginBackground","Login background"]].map(([kind,label])=><label className="upload-box" key={kind}>{label}<input type="file" accept="image/*,.ico" onChange={e=>upload(kind,e.target.files?.[0])}/></label>)}</div></section><section className="panel"><div className="panel-heading"><div><h2>Offline alerts</h2><p>Email plus an iOS Shortcuts-compatible webhook.</p></div></div><form onSubmit={saveNotifications}><Field label="Alert email" name="emailTo" type="email" value={notifications.email_to}/><Field label="Webhook URL" name="webhookUrl" type="url" value={notifications.webhook_url}/><div className="form-grid"><Field label="Offline after minutes" name="offlineMinutes" type="number" value={notifications.offline_minutes}/><Field label="Renewal warning days" name="renewalDays" type="number" value={notifications.renewal_days}/></div><button className="primary-button">Save alerts</button></form><hr/><h3>Cloudflare API tokens</h3>{connections.map(c=><div className="connection" key={c.id}><span><b>{c.name}</b><small>{c.account_hint||"Token verified"}</small></span><button className="danger-text" onClick={()=>removeConnection(c)}>Delete</button></div>)}{!connections.length&&<small>No Cloudflare connections saved.</small>}</section></div>}
