"use client";

import { FormEvent, useCallback, useEffect, useMemo, useState } from "react";

type User = { id: string; name: string; email: string; role: "admin"|"operator"|"viewer"; active?: boolean };
type Branding = Record<string, string | number | null>;
type Domain = { id:string; name:string; tld?:string; provider?:string; current_price?:number; registered_at?:string; last_renewed_at?:string; expires_at?:string; renewal_price?:number; currency:string; hosting?:string; dns_provider?:string; notes?:string; free_tier:boolean; cloudflare_connection_id?:string; cloudflare_connection_name?:string; subdomain_count:number };
type Subdomain = { id:string; name:string; dns_name?:string; record_type?:string; service?:string; host?:string; path?:string; ipv4?:string; proxied?:boolean; source:string; notes?:string };
type Server = { id:string; agent_id:string; name:string; location?:string; os?:string; ipv4?:string; wan_ipv4?:string; last_seen_at?:string; enrolled_at?:string; cpu?:number; ram?:number; temperature?:number; uptime_seconds?:number; disks?:Array<{device:string;mount:string;total:number;used:number;percent:number}>; proxies?:Array<Record<string,string>>; online?:boolean };
type Alert = { id:string; severity:string; title:string; message:string; resolved_at?:string; created_at:string };
type Connection = { id:string; name:string; account_hint?:string };
type View = "overview"|"domains"|"servers"|"alerts"|"users"|"settings";

const nav: Array<[View,string,string]> = [["overview","Overview","⌂"],["domains","Domains","◎"],["servers","Servers","▤"],["alerts","Alerts","!"],["users","Users","♙"],["settings","Settings","⚙"]];
const money = new Intl.NumberFormat("en-IN", { style:"currency", currency:"INR", maximumFractionDigits:0 });
const bytes = (value=0) => `${(value / 1073741824).toFixed(value > 107374182400 ? 0 : 1)} GB`;
const daysUntil = (value?:string) => value ? Math.ceil((new Date(value).getTime()-Date.now())/86400000) : null;
const uptime = (seconds=0) => seconds ? `${Math.floor(seconds/86400)}d ${Math.floor((seconds%86400)/3600)}h` : "Waiting";

async function api(url:string, options?:RequestInit) {
  const response = await fetch(url, { cache:"no-store", ...options });
  const data = response.headers.get("content-type")?.includes("json") ? await response.json() : null;
  if (!response.ok) throw new Error(data?.error || `Request failed (${response.status})`);
  return data;
}

export default function Dashboard({ initialUser, initialBranding }: { initialUser:User; initialBranding:Branding }) {
  const [view,setView]=useState<View>("overview"), [dark,setDark]=useState(()=>typeof window!=="undefined"&&localStorage.getItem("nexus-theme")==="dark"), [mobile,setMobile]=useState(false);
  const [domains,setDomains]=useState<Domain[]>([]), [servers,setServers]=useState<Server[]>([]), [alerts,setAlerts]=useState<Alert[]>([]);
  const [users,setUsers]=useState<User[]>([]), [connections,setConnections]=useState<Connection[]>([]), [branding,setBranding]=useState(initialBranding);
  const [notifications,setNotifications]=useState<Record<string,string|number|null>>({}), [query,setQuery]=useState(""), [busy,setBusy]=useState(false);
  const [toast,setToast]=useState(""), [modal,setModal]=useState<string|null>(null), [selected,setSelected]=useState<Domain|null>(null), [subdomains,setSubdomains]=useState<Subdomain[]>([]), [dns,setDns]=useState<Array<Record<string,unknown>>>([]), [install,setInstall]=useState("");

  const tell=(message:string)=>{setToast(message);window.setTimeout(()=>setToast(""),3500)};
  const load=useCallback(async()=>{
    const jobs=[api("/api/domains"),api("/api/servers"),api("/api/alerts"),api("/api/branding"),api("/api/cloudflare/connections")];
    const [d,s,a,b,c]=await Promise.all(jobs);
    setDomains(d.domains);setServers(s.servers.map((item:Server)=>({...item,online:Boolean(item.last_seen_at&&Date.now()-new Date(item.last_seen_at).getTime()<180000)})));setAlerts(a.alerts);setBranding(b.branding);setConnections(c.connections);
    if(initialUser.role==="admin") {
      const [u,n]=await Promise.all([api("/api/users"),api("/api/settings/notifications")]);setUsers(u.users);setNotifications(n.settings);
    }
  },[initialUser.role]);
  useEffect(()=>{const initial=window.setTimeout(()=>load().catch(e=>tell(e.message)),0);const timer=window.setInterval(()=>load().catch(()=>{}),30000);return()=>{clearTimeout(initial);clearInterval(timer)}},[load]);
  useEffect(()=>{document.documentElement.classList.toggle("dark",dark);localStorage.setItem("nexus-theme",dark?"dark":"light")},[dark]);
  const style={"--primary":String(branding.primary_color||"#2563eb"),"--accent":String(branding.accent_color||"#7c3aed"),"--font":String(branding.font_family||"Inter"),"--base-size":`${branding.base_font_size||15}px`} as React.CSSProperties;
  const filtered=useMemo(()=>domains.filter(d=>`${d.name} ${d.provider} ${d.hosting} ${d.dns_provider}`.toLowerCase().includes(query.toLowerCase())),[domains,query]);
  const online=(s:Server)=>Boolean(s.online);
  const openAlerts=alerts.filter(a=>!a.resolved_at), renewalTotal=domains.reduce((sum,d)=>sum+Number(d.renewal_price||0),0);

  async function openDomain(domain:Domain){setSelected(domain);setModal("domain-detail");setDns([]);const result=await api(`/api/domains/${domain.id}`);setSubdomains(result.subdomains)}
  async function submitDomain(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);try{const f=new FormData(event.currentTarget);let connectionId=String(f.get("cloudflareConnectionId")||"")||null;const token=String(f.get("cloudflareToken")||"");if(token){const c=await api("/api/cloudflare/connections",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name:f.get("cloudflareName")||f.get("name"),token})});connectionId=c.id}const payload={name:f.get("name"),provider:f.get("provider"),currentPrice:Number(f.get("currentPrice"))||null,registeredAt:f.get("registeredAt")||null,lastRenewedAt:f.get("lastRenewedAt")||null,expiresAt:f.get("expiresAt")||null,renewalPrice:Number(f.get("renewalPrice"))||null,currency:f.get("currency")||"INR",hosting:f.get("hosting"),dnsProvider:f.get("dnsProvider"),notes:f.get("notes"),freeTier:f.get("freeTier")==="on",cloudflareConnectionId:connectionId};await api(selected?`/api/domains/${selected.id}`:"/api/domains",{method:selected?"PATCH":"POST",headers:{"content-type":"application/json"},body:JSON.stringify(payload)});setModal(null);setSelected(null);await load();tell(selected?"Domain updated":"Domain added")}catch(e){tell((e as Error).message)}finally{setBusy(false)}}
  async function renew(domain:Domain){const start=domain.expires_at?new Date(domain.expires_at):new Date();start.setFullYear(start.getFullYear()+1);await api(`/api/domains/${domain.id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({name:domain.name,provider:domain.provider,currentPrice:domain.current_price,registeredAt:domain.registered_at,lastRenewedAt:new Date().toISOString().slice(0,10),expiresAt:start.toISOString().slice(0,10),renewalPrice:domain.renewal_price,currency:domain.currency,hosting:domain.hosting,dnsProvider:domain.dns_provider,notes:domain.notes,freeTier:domain.free_tier,cloudflareConnectionId:domain.cloudflare_connection_id,markRenewed:true})});await load();tell("Renewal recorded")}
  async function submitSubdomain(event:FormEvent<HTMLFormElement>){event.preventDefault();if(!selected)return;const f=new FormData(event.currentTarget);const id=String(f.get("id")||"");await api(id?`/api/subdomains/${id}`:`/api/domains/${selected.id}/subdomains`,{method:id?"PATCH":"POST",headers:{"content-type":"application/json"},body:JSON.stringify(Object.fromEntries(f))});const result=await api(`/api/domains/${selected.id}`);setSubdomains(result.subdomains);setModal("domain-detail");tell("Subdomain saved")}
  async function addServer(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);try{const f=new FormData(event.currentTarget);const result=await api("/api/servers",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(Object.fromEntries(f))});setInstall(result.installCommand);setModal("install");await load()}catch(e){tell((e as Error).message)}finally{setBusy(false)}}
  async function importExcel(file?:File){if(!file)return;const form=new FormData();form.set("file",file);setBusy(true);try{const r=await api("/api/domains/import",{method:"POST",body:form});await load();tell(`${r.imported} domain rows imported`)}catch(e){tell((e as Error).message)}finally{setBusy(false)}}
  async function submitUser(event:FormEvent<HTMLFormElement>){event.preventDefault();const f=new FormData(event.currentTarget);await api("/api/users",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(Object.fromEntries(f))});setModal(null);await load();tell("User created")}
  async function saveBranding(event:FormEvent<HTMLFormElement>){event.preventDefault();const f=new FormData(event.currentTarget);await api("/api/branding",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify(Object.fromEntries(f))});await load();tell("Branding updated")}
  async function uploadBrand(kind:string,file?:File){if(!file)return;const form=new FormData();form.set("kind",kind);form.set("file",file);await api("/api/branding",{method:"POST",body:form});await load();tell("Image uploaded")}
  async function saveNotifications(event:FormEvent<HTMLFormElement>){event.preventDefault();await api("/api/settings/notifications",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify(Object.fromEntries(new FormData(event.currentTarget)))});await load();tell("Alert settings saved")}

  return <div className="app-shell" style={style}>
    <aside className={`sidebar ${mobile?"open":""}`}>
      <button className="mobile-close" onClick={()=>setMobile(false)}>×</button>
      <div className="brand">{branding.logo_path?<img src={String(branding.logo_path)} alt=""/>:<span className="brand-mark">N</span>}<span><strong>{branding.brand_name||"Nexus"}</strong><small>{branding.brand_tagline}</small></span></div>
      <nav><p className="nav-label">Workspace</p>{nav.filter(([id])=>id!=="users"||initialUser.role==="admin").map(([id,label,icon])=><button key={id} className={view===id?"active":""} onClick={()=>{setView(id);setMobile(false)}}><span>{icon}</span>{label}{id==="alerts"&&openAlerts.length>0?<b className="nav-badge">{openAlerts.length}</b>:null}</button>)}</nav>
      <div className="sidebar-card"><span className="pulse-dot"/><div><strong>Monitoring active</strong><small>{servers.filter(online).length} of {servers.length} agents online</small></div></div>
      <div className="profile"><div className="avatar">{initialUser.name.split(" ").map(x=>x[0]).slice(0,2).join("")}</div><div><strong>{initialUser.name}</strong><small>{initialUser.role}</small></div><button onClick={async()=>{await api("/api/auth/logout",{method:"POST"});location.href="/login"}}>↪</button></div>
    </aside>
    <main><header className="topbar"><button className="menu-button" onClick={()=>setMobile(true)}>☰</button><label className="search">⌕<input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search domains, servers, IPs…"/></label><div className="top-actions"><button className="icon-button" onClick={()=>setDark(!dark)}>{dark?"☀":"☾"}</button><button className="primary-button" onClick={()=>{setSelected(null);setModal(view==="domains"?"domain-form":"server-form")}}>＋ Add {view==="domains"?"domain":"server"}</button></div></header>
      <div className="content"><section className="welcome"><div><p className="eyebrow">Infrastructure command center</p><h1>{view==="overview"?`Good ${new Date().getHours()<12?"morning":"evening"}, ${initialUser.name.split(" ")[0]}.`:nav.find(x=>x[0]===view)?.[1]}</h1><p>{view==="overview"?"Live infrastructure, renewals, alerts, and ownership in one place.":"Every control on this page is connected to real data."}</p></div><button className="secondary-button" onClick={()=>load().then(()=>tell("Data refreshed"))}>↻ Refresh</button></section>
      {view==="overview"&&<><section className="kpi-grid"><Kpi label="Managed domains" value={String(domains.length)} note={`${domains.filter(d=>(daysUntil(d.expires_at)||999)<60).length} renew within 60 days`} tone="blue"/><Kpi label="Servers online" value={`${servers.filter(online).length}/${servers.length}`} note="Live agent status" tone="purple"/><Kpi label="Annual renewals" value={money.format(renewalTotal)} note="Current portfolio estimate" tone="green"/><Kpi label="Open alerts" value={String(openAlerts.length)} note="Email and webhook enabled" tone="orange"/></section><ServerGrid servers={servers} online={online}/><DomainTable domains={filtered.slice(0,8)} openDomain={openDomain} edit={d=>{setSelected(d);setModal("domain-form")}} renew={renew}/></>}
      {view==="domains"&&<section className="panel"><div className="panel-heading"><div><h2>Domain portfolio</h2><p>{domains.length} domains imported from your master workbook</p></div><div className="button-row"><label className="secondary-button file-button">{busy?"Importing…":"Import Excel"}<input type="file" accept=".xlsx,.xlsm" onChange={e=>importExcel(e.target.files?.[0])}/></label><button className="secondary-button" onClick={()=>location.href="/api/domains/export"}>Export Excel</button><button className="primary-button" onClick={()=>{setSelected(null);setModal("domain-form")}}>＋ Add domain</button></div></div><DomainTable domains={filtered} openDomain={openDomain} edit={d=>{setSelected(d);setModal("domain-form")}} renew={renew}/></section>}
      {view==="servers"&&<><section className="panel"><div className="panel-heading"><div><h2>Server fleet</h2><p>CPU, RAM, temperature, storage, addresses, uptime, and discovered proxies</p></div><button className="primary-button" onClick={()=>setModal("server-form")}>＋ Add server</button></div><ServerGrid servers={servers} online={online} detailed/></section></>}
      {view==="alerts"&&<section className="panel"><div className="panel-heading"><div><h2>Alerts</h2><p>Offline servers and upcoming renewals</p></div></div><div className="alert-list">{alerts.map(a=><article className={a.resolved_at?"resolved":""} key={a.id}><span className={`severity ${a.severity}`}>!</span><div><strong>{a.title}</strong><p>{a.message}</p><small>{new Date(a.created_at).toLocaleString()}</small></div>{!a.resolved_at&&<button className="secondary-button" onClick={async()=>{await api("/api/alerts",{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({id:a.id,resolved:true})});await load()}}>Resolve</button>}</article>)}</div></section>}
      {view==="users"&&initialUser.role==="admin"&&<section className="panel"><div className="panel-heading"><div><h2>User management</h2><p>Admin, operator, and read-only viewer access</p></div><button className="primary-button" onClick={()=>setModal("user-form")}>＋ Add user</button></div><div className="user-grid">{users.map(u=><article key={u.id}><div className="avatar">{u.name[0]}</div><div><strong>{u.name}</strong><p>{u.email}</p></div><span className="role-pill">{u.role}</span><button onClick={async()=>{await api(`/api/users/${u.id}`,{method:"PATCH",headers:{"content-type":"application/json"},body:JSON.stringify({active:!u.active})});await load()}}>{u.active===false?"Enable":"Disable"}</button></article>)}</div></section>}
      {view==="settings"&&<Settings branding={branding} notifications={notifications} connections={connections} saveBranding={saveBranding} saveNotifications={saveNotifications} upload={uploadBrand}/>}<footer>{branding.brand_name||"Nexus"} · PostgreSQL backed · Agent API v2</footer></div></main>
    {toast&&<div className="toast">{toast}</div>}
    {modal&&<div className="modal-backdrop" onMouseDown={()=>setModal(null)}><div className={`modal ${modal==="domain-detail"?"wide":""}`} onMouseDown={e=>e.stopPropagation()}><button className="modal-close" onClick={()=>setModal(null)}>×</button>
      {modal==="domain-form"&&<DomainForm domain={selected} connections={connections} submit={submitDomain} busy={busy}/>} {modal==="server-form"&&<ServerForm submit={addServer} busy={busy}/>} {modal==="user-form"&&<UserForm submit={submitUser}/>} {modal==="install"&&<Install command={install}/>} {modal==="domain-detail"&&selected&&<DomainDetail domain={selected} subdomains={subdomains} dns={dns} add={()=>setModal("subdomain-form")} edit={s=>{sessionStorage.setItem("edit-subdomain",JSON.stringify(s));setModal("subdomain-form")}} loadDns={async()=>{const r=await api(`/api/domains/${selected.id}/dns`);setDns(r.records)}} sync={async()=>{const r=await api(`/api/domains/${selected.id}/dns`,{method:"POST"});const detail=await api(`/api/domains/${selected.id}`);setSubdomains(detail.subdomains);tell(`${r.imported} Cloudflare records synced`)}}/>} {modal==="subdomain-form"&&selected&&<SubdomainForm submit={submitSubdomain}/>}</div></div>}
  </div>
}

function Kpi({label,value,note,tone}:{label:string;value:string;note:string;tone:string}){return <article className={`kpi ${tone}`}><span>{label}</span><strong>{value}</strong><small>{note}</small></article>}
function DomainTable({domains,openDomain,edit,renew}:{domains:Domain[];openDomain:(d:Domain)=>void;edit:(d:Domain)=>void;renew:(d:Domain)=>void}){return <div className="table-wrap"><table><thead><tr><th>Domain</th><th>Provider</th><th>Hosting</th><th>Expires</th><th>Time left</th><th>Renewal</th><th>Actions</th></tr></thead><tbody>{domains.map(d=>{const days=daysUntil(d.expires_at);return <tr key={d.id} onClick={()=>openDomain(d)}><td><strong>{d.name}</strong><small>{d.dns_provider||"DNS not set"} · {d.subdomain_count||0} subdomains</small></td><td>{d.provider||"—"}</td><td>{d.hosting||"Unassigned"}</td><td>{d.expires_at||"—"}</td><td><span className={`days-pill ${(days||999)<60?"urgent":(days||999)<180?"soon":"safe"}`}>{days==null?"Unknown":days<0?`${Math.abs(days)}d overdue`:`${days} days`}</span></td><td>{d.renewal_price?money.format(d.renewal_price):d.free_tier?"Free":"—"}</td><td><div className="row-actions"><button onClick={e=>{e.stopPropagation();edit(d)}}>Edit</button><button onClick={e=>{e.stopPropagation();renew(d)}}>Renewed</button></div></td></tr>})}</tbody></table>{!domains.length&&<div className="empty-state">No domains found.</div>}</div>}
function ServerGrid({servers,online,detailed}:{servers:Server[];online:(s:Server)=>boolean;detailed?:boolean}){return <div className="server-grid">{servers.map(s=><article className="server-card" key={s.id}><div className="server-title"><span className={`server-status ${online(s)?"online":"offline"}`}/><div><h3>{s.name}</h3><p>{s.ipv4||"No LAN IP"} · WAN {s.wan_ipv4||"waiting"}</p></div><span className="role-pill">{online(s)?"Online":"Offline"}</span></div><div className="metric-row"><Metric label="CPU" value={Number(s.cpu||0)}/><Metric label="RAM" value={Number(s.ram||0)}/><Metric label="TEMP" value={s.temperature==null?null:Number(s.temperature)} suffix="°C"/></div><div className="server-meta"><span>Uptime <b>{uptime(Number(s.uptime_seconds||0))}</b></span><span>OS <b>{s.os||"Waiting"}</b></span><span>Agent <b>{s.enrolled_at?"Enrolled":"Pending"}</b></span></div>{detailed&&<><h4>Storage</h4><div className="disk-list">{(s.disks||[]).map(d=><div key={`${d.device}${d.mount}`}><span>{d.mount} <small>{d.device}</small></span><b>{d.percent}% · {bytes(d.used)} / {bytes(d.total)}</b></div>)}{!(s.disks||[]).length&&<small>Waiting for agent disk inventory</small>}</div><p className="proxy-count">{(s.proxies||[]).length} services and proxy routes discovered</p></>}</article>)}{!servers.length&&<div className="empty-state">Add a server to generate its one-time agent installation command.</div>}</div>}
function Metric({label,value,suffix="%"}:{label:string;value:number|null;suffix?:string}){return <div><span>{label}</span><strong>{value==null?"N/A":`${Math.round(value)}${suffix}`}</strong><i><b style={{width:`${Math.min(100,value||0)}%`}}/></i></div>}
function Field({label,name,type="text",value,required,children}:{label:string;name:string;type?:string;value?:string|number|null;required?:boolean;children?:React.ReactNode}){return <label>{label}{children||<input name={name} type={type} defaultValue={value??""} required={required}/>}</label>}
function DomainForm({domain,connections,submit,busy}:{domain:Domain|null;connections:Connection[];submit:(e:FormEvent<HTMLFormElement>)=>void;busy:boolean}){return <><p className="eyebrow">Portfolio record</p><h2>{domain?"Edit domain":"Add domain"}</h2><form onSubmit={submit}><div className="form-grid"><Field label="Domain" name="name" value={domain?.name} required/><Field label="Provider" name="provider" value={domain?.provider}/><Field label="Registration date" name="registeredAt" type="date" value={domain?.registered_at}/><Field label="Last renewed" name="lastRenewedAt" type="date" value={domain?.last_renewed_at}/><Field label="Expiry date" name="expiresAt" type="date" value={domain?.expires_at}/><Field label="Renewal price" name="renewalPrice" type="number" value={domain?.renewal_price}/><Field label="Current price" name="currentPrice" type="number" value={domain?.current_price}/><Field label="Currency" name="currency" value={domain?.currency||"INR"}/><Field label="Hosting" name="hosting" value={domain?.hosting}/><Field label="DNS provider" name="dnsProvider" value={domain?.dns_provider}/><Field label="Cloudflare connection" name="cloudflareConnectionId"><select name="cloudflareConnectionId" defaultValue={domain?.cloudflare_connection_id||""}><option value="">None</option>{connections.map(c=><option value={c.id} key={c.id}>{c.name}</option>)}</select></Field><label className="check"><input type="checkbox" name="freeTier" defaultChecked={domain?.free_tier}/>Free-tier domain</label></div><details><summary>Add a new Cloudflare API token</summary><div className="form-grid"><Field label="Connection name" name="cloudflareName"/><Field label="Scoped API token" name="cloudflareToken" type="password"/></div></details><Field label="Notes" name="notes"><textarea name="notes" defaultValue={domain?.notes||""}/></Field><button className="primary-button wide" disabled={busy}>{busy?"Saving…":"Save domain"}</button></form></>}
function ServerForm({submit,busy}:{submit:(e:FormEvent<HTMLFormElement>)=>void;busy:boolean}){return <><p className="eyebrow">Plug-and-play agent</p><h2>Add a server</h2><p>Create the record, then run the one-time command on that server.</p><form onSubmit={submit}><Field label="Server name" name="name" required/><div className="form-grid"><Field label="Known IPv4 (optional)" name="ipv4"/><Field label="Location" name="location"/><Field label="Operating system" name="os"/></div><button className="primary-button wide" disabled={busy}>{busy?"Creating…":"Create and generate agent command"}</button></form></>}
function Install({command}:{command:string}){return <><p className="eyebrow">Server enrollment</p><h2>Install the Nexus agent</h2><p>Run this once as a sudo-capable user. The enrollment token expires in 24 hours and is exchanged for a permanent revocable agent credential.</p><pre className="command">{command}</pre><button className="primary-button wide" onClick={()=>navigator.clipboard.writeText(command)}>Copy command</button></>}
function UserForm({submit}:{submit:(e:FormEvent<HTMLFormElement>)=>void}){return <><p className="eyebrow">Access control</p><h2>Add user</h2><form onSubmit={submit}><Field label="Name" name="name" required/><Field label="Email" name="email" type="email" required/><Field label="Temporary password (12+ characters)" name="password" type="password" required/><Field label="Role" name="role"><select name="role"><option value="viewer">Viewer</option><option value="operator">Operator</option><option value="admin">Administrator</option></select></Field><button className="primary-button wide">Create user</button></form></>}
function SubdomainForm({submit}:{submit:(e:FormEvent<HTMLFormElement>)=>void}){const saved=typeof window!=="undefined"?sessionStorage.getItem("edit-subdomain"):null;const s=saved?JSON.parse(saved):{};if(saved)sessionStorage.removeItem("edit-subdomain");return <><p className="eyebrow">Route record</p><h2>{s.id?"Edit":"Add"} subdomain</h2><form onSubmit={submit}><input type="hidden" name="id" value={s.id||""}/><div className="form-grid"><Field label="Full subdomain" name="name" value={s.name} required/><Field label="DNS name" name="dnsName" value={s.dns_name}/><Field label="Record type" name="recordType" value={s.record_type}/><Field label="Service" name="service" value={s.service}/><Field label="Host / server" name="host" value={s.host}/><Field label="Path or proxy target" name="path" value={s.path}/><Field label="IPv4" name="ipv4" value={s.ipv4}/></div><Field label="Notes" name="notes"><textarea name="notes" defaultValue={s.notes||""}/></Field><button className="primary-button wide">Save subdomain</button></form></>}
function DomainDetail({domain,subdomains,dns,add,edit,loadDns,sync}:{domain:Domain;subdomains:Subdomain[];dns:Array<Record<string,unknown>>;add:()=>void;edit:(s:Subdomain)=>void;loadDns:()=>void;sync:()=>void}){return <><p className="eyebrow">Domain overview</p><h2>{domain.name}</h2><div className="detail-grid"><span>Provider<b>{domain.provider||"—"}</b></span><span>Registered<b>{domain.registered_at||"—"}</b></span><span>Expires<b>{domain.expires_at||"—"}</b></span><span>Renewal<b>{domain.renewal_price?money.format(domain.renewal_price):domain.free_tier?"Free":"—"}</b></span><span>DNS provider<b>{domain.dns_provider||"—"}</b></span><span>Hosting<b>{domain.hosting||"Unassigned"}</b></span></div><div className="panel-heading compact"><div><h3>Subdomains</h3><p>Cloudflare DNS plus agent-discovered hosts and paths</p></div><div className="button-row"><button className="secondary-button" onClick={loadDns}>View DNS records</button><button className="secondary-button" onClick={sync}>Sync Cloudflare</button><button className="primary-button" onClick={add}>＋ Add</button></div></div><div className="table-wrap"><table><thead><tr><th>Subdomain</th><th>Type</th><th>Service</th><th>Host</th><th>Path / Target</th><th>IPv4</th><th/></tr></thead><tbody>{subdomains.map(s=><tr key={s.id}><td><strong>{s.name}</strong><small>{s.source}</small></td><td>{s.record_type||"—"}</td><td>{s.service||"—"}</td><td>{s.host||"—"}</td><td>{s.path||"—"}</td><td>{s.ipv4||"—"}</td><td><button onClick={()=>edit(s)}>Edit</button></td></tr>)}</tbody></table></div>{dns.length>0&&<><h3>Live Cloudflare DNS records</h3><div className="dns-list">{dns.map((r,i)=><code key={i}>{String(r.type)} {String(r.name)} → {String(r.content)} {r.proxied?"(proxied)":""}</code>)}</div></>}</>}
function Settings({branding,notifications,connections,saveBranding,saveNotifications,upload}:{branding:Branding;notifications:Record<string,string|number|null>;connections:Connection[];saveBranding:(e:FormEvent<HTMLFormElement>)=>void;saveNotifications:(e:FormEvent<HTMLFormElement>)=>void;upload:(kind:string,file?:File)=>void}){return <div className="settings-grid"><section className="panel"><div className="panel-heading"><div><h2>Branding and theme</h2><p>Names, colors, typography, and images</p></div></div><form onSubmit={saveBranding}><div className="form-grid"><Field label="Brand name" name="brandName" value={branding.brand_name}/><Field label="Tagline" name="brandTagline" value={branding.brand_tagline}/><Field label="Primary color" name="primaryColor" type="color" value={branding.primary_color}/><Field label="Accent color" name="accentColor" type="color" value={branding.accent_color}/><Field label="Font" name="fontFamily"><select name="fontFamily" defaultValue={String(branding.font_family||"Inter")}><option>Inter</option><option>Arial</option><option>Georgia</option><option>Verdana</option><option>Tahoma</option><option>Trebuchet MS</option><option>Courier New</option></select></Field><Field label="Base font size" name="baseFontSize" type="number" value={branding.base_font_size}/></div><button className="primary-button">Save theme</button></form><div className="upload-grid">{[["logo","Dashboard logo"],["loginLogo","Login logo"],["favicon","Favicon"],["loginBackground","Login background"]].map(([kind,label])=><label className="upload-box" key={kind}>{label}<input type="file" accept="image/*,.ico" onChange={e=>upload(kind,e.target.files?.[0])}/></label>)}</div></section><section className="panel"><div className="panel-heading"><div><h2>Offline alerts</h2><p>Email plus an iOS-compatible webhook (Pushcut, Pushover, ntfy, or automation bridge)</p></div></div><form onSubmit={saveNotifications}><Field label="Alert email" name="emailTo" type="email" value={notifications.email_to}/><Field label="Webhook URL" name="webhookUrl" type="url" value={notifications.webhook_url}/><div className="form-grid"><Field label="Offline after minutes" name="offlineMinutes" type="number" value={notifications.offline_minutes}/><Field label="Renewal warning days" name="renewalDays" type="number" value={notifications.renewal_days}/></div><button className="primary-button">Save alerts</button></form><hr/><h3>Cloudflare connections</h3>{connections.map(c=><p className="connection" key={c.id}><b>{c.name}</b><span>{c.account_hint||"Token verified"}</span></p>)}<small>Add additional tokens while editing a domain. Secrets are encrypted before storage.</small></section></div>}
